# Generated by Django 6.0.3 on 2026-03-20 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('news', 'News'), ('report', 'Match Report'), ('highlight', 'Highlight'), ('transfer', 'Transfer'), ('award', 'Award')], default='news', max_length=15)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=300)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('stadium', models.CharField(default='TATU Arena', max_length=100)),
                ('week', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished')], default='upcoming', max_length=10)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('minute', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.season')),
            ],
            options={
                'ordering': ['-match_date', '-match_time'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('faculty', models.CharField(blank=True, max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('primary_color', models.CharField(default='#e8001d', max_length=7)),
                ('secondary_color', models.CharField(default='#0a0d16', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.season')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('yellow', 'Yellow Card'), ('red', 'Red Card'), ('sub', 'Substitution'), ('own_goal', 'Own Goal'), ('penalty', 'Penalty')], max_length=15)),
                ('player_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.team')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team'),
        ),
        migrations.CreateModel(
            name='LeagueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_diff', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('form', models.CharField(default='', max_length=10)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.team')),
            ],
            options={
                'ordering': ['-points', '-goal_diff', '-goals_for'],
                'unique_together': {('season', 'team')},
            },
        ),
    ]
