# Generated by Django 5.0.3 on 2026-03-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_match_stream_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguetable',
            options={'ordering': ['-points', '-goal_diff', '-goals_for'], 'verbose_name': 'Liga jadvali', 'verbose_name_plural': 'Liga jadvali'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-match_date', '-match_time'], 'verbose_name': "O'yin", 'verbose_name_plural': "O'yinlar"},
        ),
        migrations.AlterModelOptions(
            name='matchevent',
            options={'ordering': ['minute'], 'verbose_name': "O'yin hodisasi", 'verbose_name_plural': "O'yin hodisalari"},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-start_date'], 'verbose_name': 'Mavsum', 'verbose_name_plural': 'Mavsumlar'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Jamoa', 'verbose_name_plural': 'Jamoalar'},
        ),
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/', verbose_name='Video fayl'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Mehmon gollari'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team', verbose_name='Mehmon jamoasi'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Uy gollari'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team', verbose_name='Uy jamoasi'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_time',
            field=models.TimeField(verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='match',
            name='minute',
            field=models.PositiveIntegerField(default=0, verbose_name='Daqiqa'),
        ),
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.season', verbose_name='Mavsum'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stadium',
            field=models.CharField(default='TATU Maydon', max_length=100, verbose_name='Stadium'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Kutilmoqda'), ('live', 'Jonli'), ('finished', 'Tugagan')], default='upcoming', max_length=10, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stream_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Jonli efir kaliti'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stream_url',
            field=models.URLField(blank=True, help_text='YouTube embed URL (jonli efir uchun)', null=True, verbose_name='YouTube jonli havola'),
        ),
        migrations.AlterField(
            model_name='match',
            name='week',
            field=models.PositiveIntegerField(default=1, verbose_name='Hafta'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Gol'), ('yellow', 'Sariq karta'), ('red', 'Qizil karta'), ('sub', 'Almashtirish'), ('own_goal', "O'z goli"), ('penalty', 'Penalti')], max_length=15, verbose_name='Hodisa turi'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.match', verbose_name="O'yin"),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='minute',
            field=models.PositiveIntegerField(verbose_name='Daqiqa'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='player_name',
            field=models.CharField(max_length=100, verbose_name='Futbolchi'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.team', verbose_name='Jamoa'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('news', 'Yangilik'), ('report', "O'yin hisoboti"), ('highlight', 'Taqdimot'), ('transfer', 'Transfer'), ('award', 'Mukofot')], default='news', max_length=15, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Muqova rasmi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, max_length=300, verbose_name='Qisqacha'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Tanlangan'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Chop etilgan'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube embed URL (masalan: https://www.youtube.com/embed/xxx)', null=True, verbose_name='YouTube video URL'),
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateField(verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='season',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Faol mavsum'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Mavsum nomi'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='team',
            name='faculty',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='Logotip'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Jamoa nomi'),
        ),
        migrations.AlterField(
            model_name='team',
            name='primary_color',
            field=models.CharField(default='#cc1a2e', max_length=7, verbose_name='Asosiy rang'),
        ),
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.season', verbose_name='Mavsum'),
        ),
        migrations.AlterField(
            model_name='team',
            name='secondary_color',
            field=models.CharField(default='#060810', max_length=7, verbose_name='Ikkinchi rang'),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='Qisqa nomi'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/images/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Post rasmi',
                'verbose_name_plural': 'Post rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
