# Generated by Django 5.0.3 on 2026-03-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_leaguetable_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='weeks_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Haftalar soni'),
        ),
    ]
