# Generated by Django 6.0.3 on 2026-03-21 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_season_archive_post_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchevent',
            options={'ordering': ['minute', 'extra_minute'], 'verbose_name': "O'yin hodisasi", 'verbose_name_plural': "O'yin hodisalari"},
        ),
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('not_started', 'Boshlanmagan'), ('first_half', 'Birinchi yarim'), ('half_time', 'Tanaffus'), ('second_half', 'Ikkinchi yarim'), ('extra_time', "Qo'shimcha vaqt"), ('finished', 'Tugagan')], default='not_started', max_length=15, verbose_name='Faza'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Kutilmoqda'), ('live', 'Jonli'), ('half_time', 'Tanaffus'), ('second_half', 'Ikkinchi yarim'), ('extra_time', "Qo'shimcha vaqt"), ('finished', 'Tugagan')], default='upcoming', max_length=15, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube video URL'),
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starter', models.BooleanField(default=True, verbose_name='Asosiy tarkib')),
                ('position_x', models.FloatField(default=50.0, verbose_name='X pozitsiya (%)')),
                ('position_y', models.FloatField(default=50.0, verbose_name='Y pozitsiya (%)')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('red', 'Qizil karta'), ('sub_out', 'Almashtirildi'), ('sub_in', 'Kirib keldi')], default='active', max_length=10, verbose_name='Holat')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Raqam')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='Gollar')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='Assistlar')),
                ('yellows', models.PositiveIntegerField(default=0, verbose_name='Sariq kartalar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='core.match', verbose_name="O'yin")),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_appearances', to='core.player', verbose_name='Futbolchi')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='core.team', verbose_name='Jamoa')),
            ],
            options={
                'verbose_name': "O'yin futbolchisi",
                'verbose_name_plural': "O'yin futbolchilari",
                'ordering': ['team', 'is_starter', 'number'],
                'unique_together': {('player', 'match')},
            },
        ),
    ]
