# Generated by Django 6.0.3 on 2026-03-21 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_match_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchplayer',
            options={'ordering': ['team', 'is_starter', 'shirt_number'], 'verbose_name': "O'yin tarkibi", 'verbose_name_plural': "O'yin tarkiblari"},
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='number',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='yellows',
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='shirt_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Forma raqami'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('yellow', 'Sariq karta'), ('red', 'Qizil karta (chiqarilgan)'), ('sub_out', 'Almashtirilgan'), ('injured', 'Jarohat')], default='active', max_length=10, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_lineup', to='core.team', verbose_name='Jamoa'),
        ),
    ]
