# Generated by Django 4.2.29 on 2026-03-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_match_core_match_season__b2b2aa_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='core_match_season__b2b2aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='core_match_season__c892b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='core_match_status_b71399_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='core_match_week_73fb93_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='core_post_is_publ_cbaf3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='core_post_categor_c388af_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='core_post_created_84f629_idx',
        ),
    ]
