# Generated by Django 4.2.29 on 2026-03-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_match_core_match_season__b2b2aa_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['season', 'status'], name='core_match_season__b2b2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['season', 'match_date'], name='core_match_season__c892b8_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='core_match_status_b71399_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['week', 'season'], name='core_match_week_73fb93_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', 'season'], name='core_post_is_publ_cbaf3c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'is_published'], name='core_post_categor_c388af_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='core_post_created_84f629_idx'),
        ),
    ]
