# Generated by Django 4.2.29 on 2026-03-23 15:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_match_core_match_season__b2b2aa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/', validators=[core.models.validate_image_file], verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', validators=[core.models.validate_image_file], verbose_name='Muqova rasmi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/', validators=[core.models.validate_video_file], verbose_name='Video fayl'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='posts/images/', validators=[core.models.validate_image_file], verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/', validators=[core.models.validate_image_file], verbose_name='Logotip'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', 'minute', 'extra_minute'], name='core_matche_match_i_06b848_idx'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', 'event_type'], name='core_matche_match_i_38051b_idx'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['team', 'event_type'], name='core_matche_team_id_e498ad_idx'),
        ),
        migrations.AddIndex(
            model_name='matchplayer',
            index=models.Index(fields=['match', 'team', 'is_starter'], name='core_matchp_match_i_1366f0_idx'),
        ),
    ]
