# Generated by Django 4.2.29 on 2026-03-26 13:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_player_photo_alter_post_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60, verbose_name='Tag (kichik sarlavha)')),
                ('h1a', models.CharField(blank=True, max_length=60, null=True, verbose_name='Katta matn (1-qism)')),
                ('h1b', models.CharField(max_length=60, verbose_name='Katta matn (2-qism)')),
                ('h1c', models.CharField(max_length=60, verbose_name='Katta matn (3-qism)')),
                ('desc', models.TextField(blank=True, verbose_name='Kichik matn (tagida)')),
                ('image', models.ImageField(upload_to='home_slides/', validators=[core.models.validate_image_file], verbose_name='Slayd rasmi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bosh sahifa slaydi',
                'verbose_name_plural': 'Bosh sahifa slaydlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
