# Generated by Django 4.2.29 on 2026-03-26 15:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_homeslides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_slides/', validators=[core.models.validate_image_file], verbose_name='Slayd rasmi'),
        ),
    ]
